### ISSUE TITLE
Support installing fwd for different apps/frameworks

### ISSUE THREAD

**Issue by fabriciojs** [fireworkweb/fwd#79]
Currently `fwd` comes with `fwd install` which is awesome for executing a Laravel application.

But, the tool is already flexible enough to work with any sort of docker-compose based application, for example, a JS/node application using Nuxt and SSR (server side rendering).

Maybe we can have something like `fwd install --laravel`, `fwd install --nuxt`, `fwd install --symfony`, etc.

**Comment by fabriciojs** [comment]
Example of docker-compose.yml for Nuxt application:

```
version: "2"
services:
  production:
    image: "${FWD_IMAGE_NODE}"
    command: ['yarn', 'start']
    volumes:
     - ${FWD_CONTEXT_PATH}:/app:cached
    environment:
      ASUSER: "${FWD_ASUSER}"
    ports:
     - "${FWD_HTTP_PORT}:8000"
  dev:
    image: "${FWD_IMAGE_NODE}"
    command: ['yarn', 'dev']
    volumes:
     - ${FWD_CONTEXT_PATH}:/app:cached
    environment:
      ASUSER: "${FWD_ASUSER}"
    ports:
     - "${FWD_HTTP_PORT}:8000"
```
